services:
  - type: web
    name: PotatoLeafDiseaseDetection
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn PotatoLeafDiseaseDetection.wsgi
